############################################################
#
# 文件微服务
# web访问端口号  约定：8004
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 512000   # 请求的文件大小限制为500kb
      max-request-size: 512000
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017
      database: news-dev

############################################################
#
# fastdfs 的配置信息
#
############################################################
fdfs:
  pool:
    max-total: 200   # 连接池最大数量
    max-total-per-key: 50  # 单个tracker最大连接数
    max-wait-millis: 5000 # 连
  connect-timeout: 1300
  so-timeout: 1300
  tracker-list[0]: 94.191.61.42:22122